server:
  port: 8080
spring:
  main:
    banner-mode: "off"
  jackson:
    property-naming-strategy: SNAKE_CASE
    deserialization:
      fail-on-unknown-properties: true
logging:
  level:
    root: INFO
    org.example.support: DEBUG
